app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('products','ProductController');
Route::resource('helicopters','HelicopterController');

Route::resource('apiproducts','API\APIProductController');

app/app/APIProduct.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class APIProduct extends Model
{
    protected $fillable = [
        'name', 'detail'
    ];
}

app/app/Http/Controllers/API/APIProductController.php
<?php

namespace App\Http\Controllers\API;

use App\APIProduct;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Pagination\LengthAwarePaginator;
use App\Http\Requests;

class APIProductController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $client = new \GuzzleHttp\Client();
       $res = $client->request('POST', 'http://localhost:8000/oauth/token', 
       [
        'json' => ['username' => 'julianpc@gmail.com',
        'password' => '123456',
        'grant_type' => 'password',
        'client_id' => '2',
        'client_secret' => 'jvogBdcKnmaBCcZrpP4ducYhdpnlLZqXjGN7mUdn']
        ]);

        $contents = $res->getBody();
        $token=(json_decode($contents , true));
        $acces_token = $token['access_token'];
   
        ////
        $client2 = new \GuzzleHttp\Client();
        $res=$client2->request('GET', 'http://localhost:8000/api/products', [
            'headers' => [
            'Authorization' => 'Bearer '.$acces_token,
            'Accept'     => 'application/json',
            ]
        ]);
        $contents =$res->getBody();
        $arrayData=(json_decode($contents , true));
        $products = $arrayData['data'];

        //print_r($products);

        // Get current page form url e.x. &page=1
        $currentPage = LengthAwarePaginator::resolveCurrentPage();
        // Create a new Laravel collection from the array data
        $itemCollection = collect($products);

        // Define how many items we want to be visible in each page
        $perPage = 5;

        // Slice the collection to get the items to display in current page
        $currentPageItems = $itemCollection->slice(($currentPage * $perPage) - $perPage, $perPage)->all();

        // Create our paginator and pass it to the view
        $paginatedItems= new LengthAwarePaginator($currentPageItems , count($itemCollection), $perPage);

        // set url path for generted links
        $paginatedItems->setPath($request->url());

        return view('apiproducts.index',['products'=> $paginatedItems]);

    }



    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('APIProducts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    $request->validate([
    'name' => 'required',
    'detail' => 'required',
    ]);

    //APIProduct::create($request->all());
    $client = new \GuzzleHttp\Client();
       $res = $client->request('POST', 'http://localhost:8000/oauth/token', 
       [
        'json' => ['username' => 'julianpc@gmail.com',
        'password' => '123456',
        'grant_type' => 'password',
        'client_id' => '2',
        'client_secret' => 'jvogBdcKnmaBCcZrpP4ducYhdpnlLZqXjGN7mUdn']
        ]);

        $contents = $res->getBody();
        $token=(json_decode($contents , true));
        $acces_token = $token['access_token'];
    ////

    $client2 = new \GuzzleHttp\Client();
    //$body['name'] = $request->input('name');
    //$body['detail'] = $request->input('detail');;

    $res=$client2->request('POST', 'http://localhost:8000/api/products', [
        'headers' => [
        'Authorization' => 'Bearer '.$acces_token,
        'Accept'     => 'application/json'],
        'json'=> [
            'name' => $request->name,
            'detail' => $request->detail
           ]

    ]);


    $contents =$res->getBody();
    $arrayData=(json_decode($contents , true));
    $products = $arrayData['data'];    

    return redirect()->route('apiproducts.index')
                ->with('success','Product created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\APIProduct  $aPIProduct
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        $id = $request->segment(2);

        $client = new \GuzzleHttp\Client();
        $res = $client->request('POST', 'http://localhost:8000/oauth/token', 
        [
         'json' => ['username' => 'julianpc@gmail.com',
         'password' => '123456',
         'grant_type' => 'password',
         'client_id' => '2',
         'client_secret' => 'jvogBdcKnmaBCcZrpP4ducYhdpnlLZqXjGN7mUdn']
         ]);
 
         $contents = $res->getBody();
         $token=(json_decode($contents , true));
         $acces_token = $token['access_token'];

         //request the product with id
         $client2 = new \GuzzleHttp\Client();
        $res=$client2->request('GET', 'http://localhost:8000/api/products/'.$id, [
        'headers' => [
        'Authorization' => 'Bearer '.$acces_token,
        'Accept'     => 'application/json'],
        ]);


    $contents =$res->getBody();
    $arrayData=(json_decode($contents , true));
    $product = $arrayData['data'];    
    //print_r($product);
        return view('apiproducts.show',compact('product'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\APIProduct  $aPIProduct
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {   
        $id = $request->segment(2);

        $client = new \GuzzleHttp\Client();
        $res = $client->request('POST', 'http://localhost:8000/oauth/token', 
        [
         'json' => ['username' => 'julianpc@gmail.com',
         'password' => '123456',
         'grant_type' => 'password',
         'client_id' => '2',
         'client_secret' => 'jvogBdcKnmaBCcZrpP4ducYhdpnlLZqXjGN7mUdn']
         ]);
 
         $contents = $res->getBody();
         $token=(json_decode($contents , true));
         $acces_token = $token['access_token'];

         //request the product with id
         $client2 = new \GuzzleHttp\Client();
        $res=$client2->request('GET', 'http://localhost:8000/api/products/'.$id, [
        'headers' => [
        'Authorization' => 'Bearer '.$acces_token,
        'Accept'     => 'application/json'],
        ]);


    $contents =$res->getBody();
    $arrayData=(json_decode($contents , true));
    $product = $arrayData['data'];    
    //print_r($product);
        return view('apiproducts.edit',compact('product'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\APIProduct  $aPIProduct
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        $id = $request->segment(2);
        //APIProduct::create($request->all());
        $client = new \GuzzleHttp\Client();
        $res = $client->request('POST', 'http://localhost:8000/oauth/token', 
        [
        'json' => ['username' => 'julianpc@gmail.com',
        'password' => '123456',
        'grant_type' => 'password',
        'client_id' => '2',
        'client_secret' => 'jvogBdcKnmaBCcZrpP4ducYhdpnlLZqXjGN7mUdn']
        ]);

        $contents = $res->getBody();
        $token=(json_decode($contents , true));
        $acces_token = $token['access_token']; 

        $client2 = new \GuzzleHttp\Client();
        //$body['name'] = $request->input('name');
        //$body['detail'] = $request->input('detail');;

        $res=$client2->request('PUT', 'http://localhost:8000/api/products/'.$id, [
            'headers' => [
            'Authorization' => 'Bearer '.$acces_token,
            'Accept'     => 'application/json'],
            'json'=> [
            'name' => $request->name,
            'detail' => $request->detail
            ]
        ]);

        $contents =$res->getBody();
        $arrayData=(json_decode($contents , true));
        $products = $arrayData['data'];    
         //print_r($products); 
         return redirect()->route('apiproducts.index')
                ->with('success','Product edited successfully.');      
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\APIProduct  $aPIProduct
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $id = $request->segment(2);
        //APIProduct::create($request->all());
        $client = new \GuzzleHttp\Client();
        $res = $client->request('POST', 'http://localhost:8000/oauth/token', 
        [
        'json' => ['username' => 'julianpc@gmail.com',
        'password' => '123456',
        'grant_type' => 'password',
        'client_id' => '2',
        'client_secret' => 'jvogBdcKnmaBCcZrpP4ducYhdpnlLZqXjGN7mUdn']
        ]);

        $contents = $res->getBody();
        $token=(json_decode($contents , true));
        $acces_token = $token['access_token']; 

        $client2 = new \GuzzleHttp\Client();
        //$body['name'] = $request->input('name');
        //$body['detail'] = $request->input('detail');;

        $res=$client2->request('DELETE', 'http://localhost:8000/api/products/'.$id, [
            'headers' => [
            'Authorization' => 'Bearer '.$acces_token,
            'Accept'     => 'application/json']
        ]);

        $contents =$res->getBody();
        $arrayData=(json_decode($contents , true));
        $products = $arrayData['data'];    
         //print_r($products); 
         return redirect()->route('apiproducts.index')
                ->with('success','Product edited successfully.');    
    }
}

app/resources/views/APIProducts/create.blade.php
@extends('APIProducts.layout')
  
@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New Product</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('apiproducts.index') }}"> Back</a>
        </div>
    </div>
</div>
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('apiproducts.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Name">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Detail:</strong>
                <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail"></textarea>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>

@endsection

app/resources/views/APIProducts/edit.blade.php
@extends('APIproducts.layout')
   
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('apiproducts.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('apiproducts.update',$product['id']) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Name:</strong>
                    <input type="text" name="name" value="{{ $product['name'] }}" class="form-control" placeholder="Name">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Detail:</strong>
                    <textarea class="form-control" style="height:150px" name="detail" placeholder="Detail">{{ $product['detail'] }}</textarea>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
   
    </form>

app/resources/views/APIProducts/index.blade.php
@extends('APIProducts.layout')
 
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>API Products</h2>
            </div>
            <div class="pull-right">
            <a class="btn btn-success" href="{{ route('apiproducts.create') }}"> Create New Produt</a>   
            </div>
        </div>
    </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Name</th>
            <th>Details</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($products as $product)
        <tr>
            <td>{{ $product['id'] }}</td>
            <td>{{ $product['name'] }}</td>
            <td>{{ $product['detail']  }}</td>
            <td>
            <form action="{{ route('apiproducts.destroy',$product['id']) }}" method="POST">
                <a class="btn btn-info" href="{{ route('apiproducts.show',$product['id']) }}">Show</a>
                <a class="btn btn-primary" href="{{ route('apiproducts.edit',$product['id']) }}">Edit</a>
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
            </td>
        </tr>
        @endforeach
    </table>

     {!! $products->links() !!}
      
@endsection

app/resources/views/APIProducts/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Laravel 5.7 CRUD Application - :)</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>
  
<div class="container">
    @yield('content')
</div>
   
</body>
</html>

app/resources/views/APIProducts/show.blade.php
@extends('apiproducts.layout')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Product</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('apiproducts.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $product['name'] }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $product['detail'] }}
            </div>
        </div>
    </div>
@endsection